-- 없어진 기록 찾기
-- https://programmers.co.kr/learn/courses/30/lessons/59042
-- https://www.w3schools.com/sqL/sql_in.asp
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_OUTS.ANIMAL_ID NOT IN (
    SELECT ANIMAL_INS.ANIMAL_ID
    FROM ANIMAL_INS
)
ORDER BY ANIMAL_OUTS.ANIMAL_ID;

-- 차집합(https://www.mysqltutorial.org/mysql-minus/)
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;

-- 있었는데요 없었습니다
-- https://programmers.co.kr/learn/courses/30/lessons/59043
-- https://www.w3schools.com/sqL/sql_join_inner.asp
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME;

