-- 없어진 기록 찾기
-- https://programmers.co.kr/learn/courses/30/lessons/59042
-- https://www.w3schools.com/sqL/sql_in.asp
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_OUTS.ANIMAL_ID NOT IN (
    SELECT ANIMAL_INS.ANIMAL_ID
    FROM ANIMAL_INS
)
ORDER BY ANIMAL_OUTS.ANIMAL_ID;

-- 차집합(https://www.mysqltutorial.org/mysql-minus/)
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;

-- 있었는데요 없었습니다
-- https://programmers.co.kr/learn/courses/30/lessons/59043
-- https://www.w3schools.com/sqL/sql_join_inner.asp
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME;

-- 오랜 기간 보호한 동물 3마리
-- https://programmers.co.kr/learn/courses/30/lessons/59044
-- 차집합(https://www.mysqltutorial.org/mysql-minus/)
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME IS NULL
ORDER BY ANIMAL_INS.DATETIME
LIMIT 3;

-- 보호소에서 중성화한 동물
-- https://programmers.co.kr/learn/courses/30/lessons/59045
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE "Intact%" 
AND (SEX_UPON_OUTCOME LIKE "Spayed%" OR SEX_UPON_OUTCOME LIKE "Neutered%")
ORDER BY ANIMAL_INS.ANIMAL_ID;


